import Head from "next/head";
import Layout from "../components/Layout";

const projects = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>프로젝트</h1>
    </Layout>
  );
};

export default projects;
